site_name: Práctica MkDocs IAW

nav:
    - Principal: index.md
    - Acerca de: about.md
    - Práctica 1: practica1.md
    - Práctica 2: practica2.md

theme:
    name: material
    language: es
    palette:
        scheme: slate
        primary: blue